[package]
name = "dsp-native-core"
version = "1.2.3"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
hex.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
ryu-js.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
